name = "game-forum"
compatibility_date = "2024-01-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "forum-db"
database_id = "150cc66a-aec8-490f-901c-aeaa0399bc2c"

[vars]
JWT_SECRET = "super_secret_jwt_key_for_game_forum_12345"
